CREATE TABLE draft_cover_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    asset_id VARCHAR(255) NOT NULL UNIQUE,
    public_id VARCHAR(255) NOT NULL UNIQUE,
    secure_url VARCHAR(2048) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_draft_cover_asset_id CHECK (asset_id ~ '[^[:space:]]'),
    CONSTRAINT ck_draft_cover_public_id CHECK (public_id ~ '^community-draft-covers/[^/]+$'),
    CONSTRAINT ck_draft_cover_secure_url CHECK (secure_url ~ '^https://')
);
CREATE INDEX ix_draft_cover_owner ON draft_cover_uploads(owner_id);
-- No legacy ownership backfill. Rollback, after reverting dependent code:
-- DROP TABLE draft_cover_uploads;
