CREATE TABLE destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_key VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_destination_key UNIQUE (destination_key),
    CONSTRAINT ck_destination_key_nonblank CHECK (destination_key ~ '[^[:space:]]'),
    CONSTRAINT ck_destination_name_nonblank CHECK (name ~ '[^[:space:]]'),
    CONSTRAINT ck_destination_country_nonblank CHECK (country ~ '[^[:space:]]')
);

CREATE TABLE external_destination_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_external_destination_mappings_destination FOREIGN KEY (destination_id)
        REFERENCES destinations(id) ON DELETE CASCADE,
    CONSTRAINT uk_external_destination_mappings_scope UNIQUE (destination_id, provider, entity_type),
    CONSTRAINT ck_external_mapping_provider CHECK (provider IN ('TRIP_COM', 'AMADEUS', 'GOOGLE')),
    CONSTRAINT ck_external_mapping_entity_type CHECK (entity_type IN ('CITY', 'AIRPORT', 'PLACE', 'REGION')),
    CONSTRAINT ck_external_mapping_id_nonblank CHECK (external_id ~ '[^[:space:]]')
);

CREATE TABLE destination_mapping_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    reason TEXT,
    fallback VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_destination_mapping_reviews_destination FOREIGN KEY (destination_id)
        REFERENCES destinations(id) ON DELETE CASCADE,
    CONSTRAINT uk_destination_mapping_reviews_scope UNIQUE (destination_id, provider, entity_type),
    CONSTRAINT ck_mapping_review_provider CHECK (provider IN ('TRIP_COM', 'AMADEUS', 'GOOGLE')),
    CONSTRAINT ck_mapping_review_entity_type CHECK (entity_type IN ('CITY', 'AIRPORT', 'PLACE', 'REGION')),
    CONSTRAINT ck_mapping_review_status CHECK (status IN ('MAPPED', 'SKIPPED')),
    CONSTRAINT ck_mapping_review_state CHECK (
        (status = 'MAPPED' AND fallback IS NULL)
        OR (status = 'SKIPPED' AND reason IS NOT NULL AND reason ~ '[^[:space:]]'
            AND fallback IS NOT NULL AND fallback = 'DEFAULT_AFFILIATE_LINK')
    )
);

ALTER TABLE itineraries ADD COLUMN destination_id BIGINT;
ALTER TABLE itineraries ADD CONSTRAINT fk_itinerary_destination
    FOREIGN KEY (destination_id) REFERENCES destinations(id) ON DELETE RESTRICT;
CREATE INDEX idx_itineraries_destination_id ON itineraries(destination_id);
